#!/usr/bin/env python3
"""
Generated by AI Navigator
URL: https://morganstanley.tal.net/vx/lang-en-GB/mobile-0/brand-2/candidate/jobboard/vacancy/1/adv/
Generated at: 2025-09-30T19:47:44.067321
"""

import logging
import sys
import os

# Add the parent directory to the path to import our modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from playwright_scraper import PlaywrightScraperSync
from supabase_database import SupabaseDatabaseManager

def setup_logging():
    """Setup logging for the scraper."""
    import os
    os.makedirs('logs', exist_ok=True)
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(f'logs/morgan_stanley_scraper.log'),
            logging.StreamHandler()
        ]
    )


def get_scraper_config():
    """Get the scraper configuration for {company_name}."""
    return {
        'company_name': 'Morgan Stanley',
        'scrape_url': 'https://morganstanley.tal.net/vx/lang-en-GB/mobile-0/brand-2/candidate/jobboard/vacancy/1/adv/',
        'job_container_selector': 'table.solr_search_list tbody tr.search_res',
        'title_selector': 'td.comm_list_tbody a.subject',
        'url_selector': 'td.comm_list_tbody a.subject',
        'description_selector': '',
        'location_selector': 'td.comm_list_tbody:last-child',
        'requirements_selector': '',
        'pagination_selector': 'div.paging span.next_links a',
        'has_dynamic_loading': False,
        'search_required': True,
        'search_input_selector': '#fulltext_field_search',
        'search_submit_selector': '#fulltext_button',
        'search_query': 'internship',
        'text_filter_keywords': '',
        'max_pages': 999  # Unlimited - will stop automatically based on end conditions
    }

def main():
    """Main scraper function."""
    setup_logging()
    logger = logging.getLogger(__name__)
    
    logger.info("Starting Morgan Stanley job scraper...")
    
    config = get_scraper_config()
    
    # Initialize database-enabled scraper
    scraper = PlaywrightScraperSync(use_database=True)
    db_manager = SupabaseDatabaseManager()
    
    # Get company info from database
    company = db_manager.get_company_by_name('Morgan Stanley')
    if not company:
        logger.error("Company '{company_name}' not found in database")
        print("Error: Company not found in database. Please add the company first.")
        return

    # Scrape jobs and get filtered HTML
    jobs, filtered_html = scraper.scrape_jobs(config['scrape_url'], config)
    
    if jobs:
        logger.info(f"Successfully scraped {len(jobs)} jobs from 'Morgan Stanley'")
        
        # Print summary
        print(f"\\n=== SCRAPING RESULTS ===")
        print(f"Company: 'Morgan Stanley'")
        print(f"URL: 'https://morganstanley.tal.net/vx/lang-en-GB/mobile-0/brand-2/candidate/jobboard/vacancy/1/adv/'")
        print(f"Jobs found: {len(jobs)}")
        print(f"Jobs saved to database: jobs.db")
        
        # Show sample jobs
        print(f"\\n=== SAMPLE JOBS ===")
        for i, job in enumerate(jobs[:3], 1):
            print(f"{i}. {job.get('title', 'No title')}")
            print(f"   Location: {job.get('location', 'Not specified')}")
            print(f"   URL: {job.get('url', 'No URL')}")
            print()
        
    else:
        logger.warning("No jobs found - scraper may need adjustment")
        print("No jobs found. The scraper configuration may need to be adjusted.")
        
        # Log failed scraper execution
        db_manager.log_scraper_execution(
            company['id'], 
            0, 
            success=False,
            error_message="No jobs found"
        )

if __name__ == "__main__":
    main()
